### ISSUE TITLE
김수한무, 마리오등 캐릭터 크기 변수화하기, 함수들 모듈화 하기

### ISSUE THREAD

**Issue by why-arong** [kookmin-university-2023-rust-team-D/rust-rakitu-game#10]

**Comment by Cocozo** [comment]
모듈화는 생각보다 쉽습니다.
bevy의 plugin기능을 사용하면 되는데, 

현제 feature/player에 있는 브랜치에 player.rs를 보면,

```rust
pub struct PlayerPlugin;

impl Plugin for PlayerPlugin {
    fn build(&self, app: &mut App) {
        app
            .add_startup_system(spawn_player)
            .add_system(player_movement)
            .add_system(cofine_player_movement);
    }
}

...
//이하 내용 동일
``` 
과 같이 내용을 따로 파일을 만들 모듈화 한 뒤, 이를
main.rs에 

```rust

mod player;

use bevy::prelude::*;
use player::PlayerPlugin;

fn main() {
    App::new()
    .add_plugins(DefaultPlugins)
    .add_plugin(PlayerPlugin)
    .add_startup_system(spawn_camera)
    .run();    
}

``` 
와 같이 붙히면 됩니다

**Comment by Cocozo** [comment]
**아래 로직이(포지션 부분)이 기존 bevy 튜토리얼과 달라  그대로 복붙하면 오류가 나므로  주의해 주세요!**

**Comment by why-arong** [comment]
> **아래 로직이(포지션 부분)이 기존 bevy 튜토리얼과 달라  그대로 복붙하면 오류가 나므로  주의해 주세요!**

베비 튜토리얼이랑 다르다는게 무슨 말이에요?

**Comment by Cocozo** [comment]
제가 드렸던  베비 튜토리얼  영상같은 경우, 카메라를 포함하여 포지션의 (0,0) 부분이 중앙에서 왼쪽 아래로 설정되어있습니다. 저는 이를 중앙에 둔다음에 코딩하였기 때문에 코드를 그대로 사용하는경우 의도가 잘못되어 동작할 수 있습니다
