### ISSUE TITLE
fearture/ui브랜치에 대한 작업에 대해서

### ISSUE THREAD

**Issue by Cocozo** [kookmin-university-2023-rust-team-D/rust-rakitu-game#15]
현재 fearture/ui 브랜치에서 모든 작업이 이루어지고 있습니다...
따라서 해당 브랜치에 대한 규약이 조금 필요 해서 이슈 올립니다.

해당 브랜치에서 작업을 하고 싶을때, 브랜치를 새로 따서 작업 후에, PR을 보내는 방식으로 진행하는것이 어떤가요?
최근에 닫힌 PR의 경우에도 다행이 컨플릭트는 없었으나, 잘못하면 컨플릭트가 크게 날 수도 있었던 경우 였습니다...!

**Comment by kimdonguk-kmu** [comment]
좋습니다

**Comment by why-arong** [comment]
네 알겠습니다. 브랜치 이름은 feature/pilmo 정도로 할까요?

**Comment by Cocozo** [comment]
넵 그래도 상관없고 아님 조금 명확하게 만들고자 하는 기능 명을 적으셔도 좋을것 같아요:)
