### ISSUE TITLE
김수한무 레벨에 따른 생성에 대해

### ISSUE THREAD

**Issue by why-arong** [kookmin-university-2023-rust-team-D/rust-rakitu-game#18]
김수한무가 처음 게임 시작했을 때는 1개
점점 시간이 지날수록 2개, 3개로 늘어나는 방식을 사용하는 것 어떨까요?

만약 동의하시면 이대로 제가 코드 짜보겠습니다.

**Comment by kimdonguk-kmu** [comment]
그것도 괜찮을 것 같네요

**Comment by why-arong** [comment]
네 알겠습니다.
