### ISSUE TITLE
플레이어간의 김수한무의 움직임 동기화

### ISSUE THREAD

**Issue by kimdonguk-kmu** [kookmin-university-2023-rust-team-D/rust-rakitu-game#24]
플레이어 움직임의 동기화는 성공했지만 김수한무의 움직임은 플레이어마다 다릅니다.
어떻게 해결해야 할까요

**Comment by why-arong** [comment]
player_movement.in_schedule(GGRSSchedule) 처럼 김수한무도 움직임에 대한 것을 ggrs가 알아야 하나봐요..
한번 이리저리 해보겠습니다

**Comment by kimdonguk-kmu** [comment]
안되면 그냥 김수한무와의 1대1은 어떨까요?
플레이어 한명은 마리오, 한명은 김수한무로 하면 설정할 필요가 없을 것 같아요

**Comment by why-arong** [comment]
만약 정 안되면 그렇게 해야할 것 같습니다!
이유는 플레이어 1, 2 들어오는 시간이 달라서 생기네요. 코드에서 플레이어끼리는 다 들어오면 컨트롤 가능하게 되어있는데 김수한무는 그런 제어가 없어서 바로 생성되고있어요.

**Comment by Cocozo** [comment]
이부분도GGRS 스케쥴에 넣어 관리할 수 있는 방법이 있을 것 같습니다. 한번 찾아보겠습니다

**Comment by kimdonguk-kmu** [comment]
저는 일단 1대1 프로그램으로 만들겠습니다
