### ISSUE TITLE
[not issue] 와... 국민대는 러스트도 학교 차원에서 학습하나요?

### ISSUE THREAD

**Issue by namse** [kookmin-university-2023-rust-team-D/rust-rakitu-game#33]
대박... 어쩌다가 bevy로 만들게 되었는지도 궁금해요!

**Comment by Cocozo** [comment]
해당 과목의 수업방식의 팀단위 발표 수업이었고, 주마다 특정 주제에 대해 팀별로 학습하고 학습한 내용을 기반으로 발표자료를 만들어 발표를 해야했습니다...! 5주간 러스트에 대해서 저희 팀끼리 공부하고, 공부내용을 공유하면서 학습했습니다... :)
저희 팀의 마지막 과제가 러스트로 멀티플레이 게임을 만들어보는 것이었는데, 이에 필요한 라이브러리를 찾다가, GGEZ와 Amethyst, bevy 를 찾았는데, 이중에서 Amethyst, bevy 가 가지고 있던 ECS 패턴을 기반으로 게임을 구성하면 좀더 빠르게 게임을 제작할 수 있을것 같아 
개발이 중단된 Amethyst는 제외하고 bevy를 사용하게 되었습니다!

**Comment by Cocozo** [comment]
아직 제대로된 도큐먼트가 없어 bevy를 뜯어보다 싶이 코딩을 해서 생각보다 험난했지만 그래도 확실히 공부는 되었네요...:)

**Comment by namse** [comment]
답변에서 약간 헷갈리는데, 러스트 과목에서 있었던 팀단위 발표 수업이라는 것인가요?

**Comment by Cocozo** [comment]
러스트 과목은 따로 없었고 최신기술관련 과목이 있습니다.
세 교수님께서 세가지 주제를 번갈아 가르치는 과목인데, 그중 러스트를 주제로 5주간 수업을 하였던 교수님이 계셨습니다!
그때 러스트를 주제로 팀단위 발표 수업을 진행하였습니다!

**Comment by namse** [comment]
그랬군요..! 큰 궁금증이 해결되었습니다 ㅎㅎ 감사합니다!
