### ISSUE TITLE
main / master 중 어떤 브렌치를 사용할까요?

### ISSUE THREAD

**Issue by Cocozo** [kookmin-university-2023-rust-team-D/rust-rakitu-game#5]
필모님께서 main 브랜치를 만드신걸로 알고 있습니다. 따라서 master 브랜치는 이제 사용할 필요가 없어졌는데, 해당 브랜치는 없에도 상관 없을까요?

**Comment by why-arong** [comment]
네 없애도 될 것 같습니다.
