### ISSUE TITLE
캐릭터 좌우 반전

### ISSUE THREAD

**Issue by why-arong** [kookmin-university-2023-rust-team-D/rust-rakitu-game#7]
마리오가 왼쪽으로 갈 땐 왼쪽 모습 오른쪽으로 갈 때는 오른쪽 모습으로 하고 싶은데 어떻게 추가하면 좋을까요??

**Comment by kimdonguk-kmu** [comment]
이미지를 좌우반전시키는 함수같은게 없다면, 좌우반전된 이미지를 하나 더 준비해서 키보드를 누르면 좌우반전된 이미지가 나오게 해야하지 않을까요?

**Comment by kimdonguk-kmu** [comment]
SpriteBundle{
                transform: Transform{
                    translation: Vec3::new(window.width() / 3.0, PLAYER_SIZE / 2.0 + PLANE, 0.0),
                    scale: Vec3::new(-3.0, 3.0, 0.0),
                    ..default()
                },
                    texture: assert_server.load("sprites/mario2.png"),
                    ..default()
            }
부분에서 scale의 x에 -1을 곱하면 이미지가 좌우반전되네요
이걸 활용하면 좋을 것 같아요

**Comment by why-arong** [comment]
해결 함
