### ISSUE TITLE
김수한무 인공지능 구현

### ISSUE THREAD

**Issue by why-arong** [kookmin-university-2023-rust-team-D/rust-rakitu-game#8]
김수한무 가 좌우로 막 움직이는 것을 일단 구현해야 할 것 같습니다.

그 다음으로는 김수한무가 거북이를 던지도록 구현

**Comment by why-arong** [comment]
이제 거북이 던지는 것 해결하면 될 것 같네요

**Comment by why-arong** [comment]
김수한무는 분노 레벨에 따라 순차적으로 생성되어야 하니까 이것도 고쳐야 합니다.

**Comment by kimdonguk-kmu** [comment]
feature/ui 브랜치에 김수한무가 거북이를 던지는 로직까지는 구현했습니다.
분노 레벨을 구현해야 합니다
