### ISSUE TITLE
enemy_movement의 작동 오류

### ISSUE THREAD

**Issue by kimdonguk-kmu** [kookmin-university-2023-rust-team-D/rust-rakitu-game#9]
enemy의 움직임을 담당하는 함수 enemy_movement를 작성하였는데, NUMBER_OF_ENEMIES가 1을 초과하게 되면 에러가 발생합니다.
김수한무가 1마리일 때만 코드가 문제없이 작동합니다.

**Comment by why-arong** [comment]
for 문으로 해결했습니다.
